---
roles:
  # Basic Galaxy
  - name: geerlingguy.firewall

  # Specify version
  - name: geerlingguy.php

  # From GitHub, with a custom name and version.
  - src: https://github.com/geerlingguy/ansible-role-passenger
    name: passenger
    version: 2.0.0

  # From a web server, with a custom name.
  #- src: https://www.example.com/ansible/roles/my-role-name.tar.gz
  #  name: my-role”
