---
- name: Install ansible

  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - ansible
      - cowsay # Because who *doesn't* want a talking cow?
