---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/api_key.yml
    - vars/discord.yml

  tasks:
    - name: Echo the API key which was injected into the env.
      shell: echo $API_KEY
      environment:
        API_KEY: "{{ myapp_api_key }}"
      register: echo_result

    - name: Show the result.
      debug: var=echo_result.stdout

  post_tasks:
    - name: Some dopey thing
      connection: local
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: "This is a message from Ansible"
        username: Ansible
